### ISSUE TITLE
Ordered list requirement for unit messing up movement

### ISSUE THREAD

**Issue by char1129** [char1129/lists-n-grids#1]
Having a hard time matching the screenshots with this one.
Putting a unit on the ol tag messes up the medium and large resolution by not allowing the second and forth row to come up at m-1-2 and l-1-2 settings.
Had to add style to html to get rid of bottom margin of h1 and list style of ordered list's li.

Please help! 

I had the sections as figures and fig captions until just recently because I was finding odd spacing between type but that hasn't seem to fix the problem (space between body and link and link to bottom of card). I will revert it back.

P.S
I don't have our TA's Github username (for Group 040). Could you add it to your response, so that I can bothe- I can reach out to her for help as well? 
_(Unless you're bored and want me to blow up your Github with s subscription of issues I'll have lol!)_ 
Thank you!

@muxlowc

![issues](https://user-images.githubusercontent.com/55107755/73049452-a4b44100-3e4a-11ea-9e86-0ab9e954abdd.jpg)

**Comment by muxlowc** [comment]
Hey @char1129 ,

So it looks like you have your Grid class on the wrong item, the grid should be on the ol, and not the main. And since the H1 kind of just floats on its own (basically a block by default), it doesn't need a unit class.

I tweaked the first few lines of code and it seemed to mostly do the trick - I added a screenshot (hope it works) for you to see the edits I made. I'll let you figure out the rest ;)

<img width="651" alt="Screen Shot 2020-01-24 at 8 58 07 AM" src="https://user-images.githubusercontent.com/59422623/73074654-1959a080-3e88-11ea-80b3-fa92555fa3ca.png">

I think Mackenzies github is mackenzierose ?

Hope this helps!
Christina

**Comment by char1129** [comment]
@muxlowc Thank you! I've been moving around the grid tag quite a bit. I'll get back into making commits more often, so you can see the back and forth/for my own records.  
I'll give that a go, and solve the problem. 😊 Have a great weekend!

**Comment by muxlowc** [comment]
@char1129 can you please close this issue if you got it sorted out?

Thanks!
